export const doctors = [
  {
    name: "Dr. John Smith",
    category: "Cardiology",
    title: "Cardiologist",
    img: "https://via.placeholder.com/150",
    fee: 500,
  },
  {
    name: "Dr. Emily Johnson",
    category: "Pediatrics",
    title: "Pediatrician",
    img: "https://via.placeholder.com/150",
    fee: 300,
  },
  {
    name: "Dr. Michael Brown",
    category: "Neurology",
    title: "Neurologist",
    img: "https://via.placeholder.com/150",
    fee: 630,
  },
  {
    name: "Dr. Sarah Lee",
    category: "Oncology",
    title: "Oncologist",
    img: "https://via.placeholder.com/150",
    fee: 1230,
  },
  {
    name: "Dr. David Wilson",
    category: "Orthopedics",
    title: "Orthopedic Surgeon",
    img: "https://via.placeholder.com/150",
    fee: 3320,
  },
  {
    name: "Dr. Jennifer Garcia",
    category: "Dermatology",
    title: "Dermatologist",
    img: "https://via.placeholder.com/150",
    fee: 1220,
  },
  {
    name: "Dr. Robert Martinez",
    category: "Gastroenterology",
    title: "Gastroenterologist",
    img: "https://via.placeholder.com/150",
    fee: 1280,
  },
  {
    name: "Dr. Laura Davis",
    category: "Endocrinology",
    title: "Endocrinologist",
    img: "https://via.placeholder.com/150",
    fee: 1230,
  },
  {
    name: "Dr. Kevin Thompson",
    category: "Urology",
    title: "Urologist",
    img: "https://via.placeholder.com/150",
    fee: 1260,
  },
  {
    name: "Dr. Jessica White",
    category: "Psychiatry",
    title: "Psychiatrist",
    img: "https://via.placeholder.com/150",
    fee: 1300,
  },
  {
    name: "Dr. Eric Green",
    category: "Pulmonology",
    title: "Pulmonologist",
    img: "https://via.placeholder.com/150",
  },
  {
    name: "Dr. Samantha Clark",
    category: "Rheumatology",
    title: "Rheumatologist",
    img: "https://via.placeholder.com/150",
    fee: 630,
  },
  {
    name: "Dr. Christopher Hill",
    category: "Ophthalmology",
    title: "Ophthalmologist",
    img: "https://via.placeholder.com/150",
    fee: 1230,
  },
  {
    name: "Dr. Maria Martinez",
    category: "Obstetrics & Gynecology",
    title: "OB/GYN",
    img: "https://via.placeholder.com/150",
    fee: 2030,
  },
  {
    name: "Dr. Daniel Taylor",
    category: "Hematology",
    title: "Hematologist",
    img: "https://via.placeholder.com/150",
    fee: 1930,
  },
  {
    name: "Dr. Patricia Young",
    category: "Allergy & Immunology",
    title: "Allergist",
    img: "https://via.placeholder.com/150",
    fee: 1830,
  },
  {
    name: "Dr. Andrew Harris",
    category: "Nephrology",
    title: "Nephrologist",
    img: "https://via.placeholder.com/150",
    fee: 1630,
  },
  {
    name: "Dr. Amanda Lewis",
    category: "Geriatrics",
    title: "Geriatrician",
    img: "https://via.placeholder.com/150",
    fee: 1430,
  },
  {
    name: "Dr. Jason Turner",
    category: "Infectious Disease",
    title: "Infectious Disease Specialist",
    img: "https://via.placeholder.com/150",
    fee: 930,
  },
  {
    name: "Dr. Rachel King",
    category: "Family Medicine",
    title: "Family Physician",
    img: "https://via.placeholder.com/150",
    fee: 1130,
  },
]

export const myData = [
  {
    id: 100,
    title: "Doctors",
    name: "One drive hospital",
    img: require("../../assets/images/hotel1.jpeg"),
  },
  {
    id: 200,
    title: "Cardiologist",
    name: "AKG hospital",
    img: require("../../assets/images/hotel2.webp"),
  },
  {
    id: 300,
    title: "Neurologist",
    name: "two ne hospital",
    img: require("../../assets/images/hotel3.jpg"),
  },
  {
    id: 400,
    title: "Orhologist",
    name: "One hospital",
    img: require("../../assets/images/hotel4.jpg"),
  },
]
